### ISSUE TITLE
Bot is issuing quote orders instead of base orders

### ISSUE THREAD

**Issue by gomme600** [queball99/CoinbasePro-Recurring-Buy#8]
I am getting this error for 2€ worth of solana : coinbasepro.exceptions.BadRequest: funds is too small. Minimum size is 5.00000000

When checking on coinbase's website it seems that 5 is the limit for quote orders, it should be placing a base order (minimum of 0.01).

The bot is unusable in this state as a minimum quote order for bitcoin is 10 for example !

**Comment by queball99** [comment]
The bot is designed to place Market orders, which do have a minimum currency amount, 10 USD is the minimum amount of BTC I can place a Market order for on the website. This is working correctly.
